### ISSUE TITLE
Add monitoring/alerting for Production CORD

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1648]
* [ ] Create #cord-monitoring Slack Channel
* [ ] Log Errors to Slack
* [ ] Log API query time
* [ ] Logrocket?
* [ ] Get failures from deployments to Slack
* [ ] Get metrics past thresholds into Slack
* [ ] Ask DB for info like locked nodes etc & report on
* [ ] Endpoint monitoring of list queries
* [ ] Endpoint monitoring of detail pages
* [ ] Endpoint monitoring of all Endpoints

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466770832) by [Unito](https://www.unito.io)
